package com.acme.finops.gateway.policy;

public enum PathOp {
    ENTER_MSG_FIELD, ENTER_LEN_DELIMITED,
    MAP_SCAN_STRING_KEY, MAP_SCAN_ANY_KEY,
    REPEATED_FIRST, REPEATED_ANY,
    ONEOF_EXPECT_FIELD,
    READ_SCALAR, READ_STRING, READ_BYTES, READ_BOOL, READ_ENUM,
    HALT
}
